install:
    - rm -rf public || exit 0

script:
    - make

# Deploy to GitHub pages
deploy:
    provider: pages
    skip_cleanup: true
    keep-history: true
    local_dir: public
    #github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: landing_page_plus
