install:
    - rm -rf public || exit 0

script:
    - PATH=$PATH:bin/ make

# Deploy to GitHub pages
deploy:
    provider: pages
    skip_cleanup: true
    keep-history: true
    local_dir: public
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    target-branch: master
    on:
        branch: landing_page_plus
